/**
 * types.ts - Shared type definitions for pace
 */

// ============================================================================
// Token Visualization Types
// ============================================================================

/**
 * Token usage severity level based on thresholds
 */
export type TokenSeverity = 'excellent' | 'good' | 'normal' | 'warning' | 'high' | 'critical';

/**
 * Custom color definitions for token severity levels
 */
export interface TokenColors {
  excellent?: string;
  good?: string;
  normal?: string;
  warning?: string;
  high?: string;
  critical?: string;
}

/**
 * Color scheme presets for token usage visualization
 */
export type ColorScheme = 'default' | 'budget' | 'efficiency' | 'accessibility' | 'custom';

/**
 * Threshold levels for multi-tier token severity
 */
export interface TokenThresholds {
  excellent?: number;
  good?: number;
  normal?: number;
  warning?: number;
  high?: number;
  critical?: number;
}

// ============================================================================
// Agent Names
// ============================================================================

/**
 * Built-in Pace agent names used by the CLI
 */
export const PACE_AGENTS = {
  CODING: 'pace-coding',
  INITIALIZER: 'pace-initializer',
  COORDINATOR: 'pace-coordinator',
  CODE_REVIEWER: 'pace-code-reviewer',
  PRACTICES_REVIEWER: 'pace-practices-reviewer',
} as const;

export type PaceAgentName = (typeof PACE_AGENTS)[keyof typeof PACE_AGENTS];

// ============================================================================
// Feature Types
// ============================================================================

export type Priority = 'critical' | 'high' | 'medium' | 'low';

export interface Feature {
  id: string;
  category: string;
  description: string;
  priority: Priority;
  steps: string[];
  passes: boolean;
  tags?: string[];
}

export interface FeatureListMetadata {
  project_name?: string;
  total_features?: number;
  passing?: number;
  failing?: number;
  last_updated?: string;
  token_usage?: TokenUsage;
  [key: string]: unknown;
}

export interface FeatureList {
  features: Feature[];
  metadata?: FeatureListMetadata;
}

/**
 * Token usage metrics for a session or collection of sessions
 *
 * Tracks the number of tokens consumed during LLM interactions, broken down
 * by input (prompts sent to the model) and output (responses from the model).
 * This data is extracted from OpenCode SDK events when available.
 *
 * @interface TokenUsage
 * @property {number} input - Number of tokens sent to the model (input/prompts)
 * @property {number} output - Number of tokens generated by the model (output/responses)
 * @property {number} total - Total tokens used (input + output)
 * @property {string} [model] - Model identifier (e.g., 'anthropic/claude-3-5-sonnet')
 *
 * @example
 * ```typescript
 * const sessionTokens: TokenUsage = {
 *   input: 1500,
 *   output: 750,
 *   total: 2250,
 *   model: 'anthropic/claude-3-5-sonnet'
 * };
 * ```
 */
export interface TokenUsage {
  input: number;
  output: number;
  total: number;
  model?: string;
}

/**
 * Model-specific token usage breakdown
 *
 * Tracks token usage separately by model tier, allowing for detailed analysis
 * of token consumption across different model types (sonnet, opus, etc).
 *
 * @interface ModelTokenUsage
 * @property {string} model - Model identifier (e.g., 'anthropic/claude-3-5-sonnet')
 * @property {number} input - Number of input tokens used by this model
 * @property {number} output - Number of output tokens used by this model
 * @property {number} total - Total tokens used by this model (input + output)
 *
 * @example
 * ```typescript
 * const sonnetUsage: ModelTokenUsage = {
 *   model: 'anthropic/claude-3-5-sonnet',
 *   input: 3000,
 *   output: 1500,
 *   total: 4500
 * };
 * ```
 */
export interface ModelTokenUsage {
  model: string;
  input: number;
  output: number;
  total: number;
}

/**
 * Model-breakdown token usage summary
 *
 * Provides a comprehensive view of token usage across different models,
 * including both individual model breakdowns and aggregate totals.
 *
 * @interface TokenUsageByModel
 * @property {ModelTokenUsage[]} byModel - Array of token usage per model
 * @property {TokenUsage} total - Aggregate token usage across all models
 *
 * @example
 * ```typescript
 * const multiModelUsage: TokenUsageByModel = {
 *   byModel: [
 *     { model: 'anthropic/claude-3-5-sonnet', input: 2000, output: 1000, total: 3000 },
 *     { model: 'anthropic/claude-3-opus', input: 1500, output: 750, total: 2250 }
 *   ],
 *   total: { input: 3500, output: 1750, total: 5250 }
 * };
 * ```
 */
export interface TokenUsageByModel {
  byModel: ModelTokenUsage[];
  total: TokenUsage;
}

/**
 * Cost breakdown for token usage
 *
 * Provides detailed cost information for input and output tokens
 * based on model pricing. Costs are calculated in USD.
 *
 * @interface CostBreakdown
 * @property {number} inputCost - Cost for input tokens in USD
 * @property {number} outputCost - Cost for output tokens in USD
 * @property {number} totalCost - Total cost (input + output) in USD
 *
 * @example
 * ```typescript
 * const costs: CostBreakdown = {
 *   inputCost: 0.075,
 *   outputCost: 0.300,
 *   totalCost: 0.375
 * };
 * ```
 */
export interface CostBreakdown {
  inputCost: number;
  outputCost: number;
  totalCost: number;
}

/**
 * Extended token usage with cost information
 *
 * Combines token usage data with calculated costs based on model pricing.
 * Used when cost estimation is enabled and model information is available.
 *
 * @interface TokenUsageWithCost
 * @property {TokenUsage} tokens - Token usage data
 * @property {string} model - Model identifier (e.g., 'anthropic/claude-3-5-sonnet')
 * @property {CostBreakdown} cost - Cost breakdown for the token usage
 *
 * @example
 * ```typescript
 * const usageWithCost: TokenUsageWithCost = {
 *   tokens: { input: 1000, output: 500, total: 1500 },
 *   model: 'anthropic/claude-3-5-sonnet',
 *   cost: { inputCost: 0.003, outputCost: 0.015, totalCost: 0.018 }
 * };
 * ```
 */
export interface TokenUsageWithCost {
  tokens: TokenUsage;
  model: string;
  cost: CostBreakdown;
}

/**
 * Model pricing information for cost calculation
 *
 * Contains per-token pricing for input and output tokens for a specific model.
 * Prices are in USD per 1,000 tokens.
 *
 * @interface ModelPricing
 * @property {number} inputPrice - Price per 1,000 input tokens in USD
 * @property {number} outputPrice - Price per 1,000 output tokens in USD
 * @property {string} provider - Model provider (e.g., 'anthropic', 'openai')
 *
 * @example
 * ```typescript
 * const claudePricing: ModelPricing = {
 *   inputPrice: 3.0,  // $3.00 per 1M input tokens
 *   outputPrice: 15.0, // $15.00 per 1M output tokens
 *   provider: 'anthropic'
 * };
 * ```
 */
export interface ModelPricing {
  inputPrice: number; // Price per 1,000 input tokens
  outputPrice: number; // Price per 1,000 output tokens
  provider: string;
}

/**
 * Cost calculation configuration
 *
 * Settings for enabling and configuring cost estimation features,
 * including custom pricing overrides and display preferences.
 *
 * @interface CostConfig
 * @property {boolean} enabled - Whether cost calculation is enabled
 * @property {Record<string, ModelPricing>} customPricing - Custom model pricing overrides
 * @property {string} currency - Currency for cost display (default: 'USD')
 * @property {number} precision - Number of decimal places for cost display (default: 4)
 *
 * @example
 * ```typescript
 * const costConfig: CostConfig = {
 *   enabled: true,
 *   customPricing: {
 *     'custom/model': { inputPrice: 2.5, outputPrice: 12.0, provider: 'custom' }
 *   },
 *   currency: 'USD',
 *   precision: 4
 * };
 * ```
 */
export interface CostConfig {
  enabled: boolean;
  customPricing?: Record<string, ModelPricing>;
  currency?: string;
  precision?: number;
}

/**
 * Token budget configuration
 *
 * Settings for configuring token budget limits and warning thresholds.
 * Helps manage token consumption and prevent unexpected costs.
 *
 * @interface TokenBudget
 * @property {number} maxTokens - Maximum number of tokens allowed per session
 * @property {number} [warningThreshold] - Percentage threshold for warnings (default: 0.8 = 80%)
 * @property {number} [criticalThreshold] - Percentage threshold for critical warnings (default: 0.95 = 95%)
 * @property {boolean} [enabled] - Whether budget tracking is enabled (default: false)
 *
 * @example
 * ```typescript
 * const tokenBudget: TokenBudget = {
 *   enabled: true,
 *   maxTokens: 100000,
 *   warningThreshold: 0.8,
 *   criticalThreshold: 0.95
 * };
 * ```
 */
export interface TokenBudget {
  enabled?: boolean;
  maxTokens?: number;
  warningThreshold?: number; // Default: 0.8 (80%)
  criticalThreshold?: number; // Default: 0.95 (95%)
}

/**
 * Budget status information
 *
 * Contains information about current token usage relative to configured budget.
 * Used for displaying warnings and budget status in various outputs.
 *
 * @interface BudgetStatus
 * @property {boolean} enabled - Whether budget tracking is enabled
 * @property {number} [currentUsage] - Current token usage count
 * @property {number} [maxTokens] - Maximum allowed tokens
 * @property {number} [percentageUsed] - Percentage of budget used (0-1)
 * @property {'none'|'warning'|'critical'|'exceeded'} [level] - Warning level based on usage
 * @property {string} [message] - Formatted warning message
 *
 * @example
 * ```typescript
 * const budgetStatus: BudgetStatus = {
 *   enabled: true,
 *   currentUsage: 85000,
 *   maxTokens: 100000,
 *   percentageUsed: 0.85,
 *   level: 'critical',
 *   message: '⚠️  Critical: 85.0% of token budget used (85,000/100,000)'
 * };
 * ```
 */
export interface BudgetStatus {
  enabled: boolean;
  currentUsage?: number;
  maxTokens?: number;
  percentageUsed?: number;
  level?: 'none' | 'warning' | 'critical' | 'exceeded';
  message?: string;
}

/**
 * Token display threshold configuration
 *
 * Configures visual indicators (color coding, warning symbols) that appear when
 * token usage exceeds certain thresholds. Helps identify expensive sessions at a glance.
 * Supports multi-tier severity levels and configurable color schemes.
 *
 * @interface TokenDisplayThresholds
 * @property {boolean} [enabled] - Whether to show visual indicators (default: true)
 * @property {ColorScheme} [colorScheme] - Color scheme preset (default: 'default')
 * @property {TokenColors} [customColors] - Custom ANSI color codes for each severity level
 * @property {TokenThresholds} [thresholds] - Multi-tier threshold values for fine-grained control
 * @property {boolean} [useAverageBasedThresholds] - Calculate thresholds based on session average (default: true)
 * @property {number} [averageMultiplierExcellent] - Multiplier for excellent threshold (default: 0.75)
 * @property {number} [averageMultiplierGood] - Multiplier for good threshold (default: 1.0)
 * @property {number} [averageMultiplierWarning] - Multiplier for warning threshold (default: 1.5)
 * @property {number} [averageMultiplierHigh] - Multiplier for high threshold (default: 1.75)
 * @property {number} [averageMultiplierCritical] - Multiplier for critical threshold (default: 2.0)
 * @property {number} [warningThreshold] - Legacy: token count above which to show warning (deprecated)
 * @property {number} [criticalThreshold] - Legacy: token count above which to show critical (deprecated)
 *
 * @example
 * ```typescript
 * // Enhanced multi-tier thresholds
 * const thresholds: TokenDisplayThresholds = {
 *   enabled: true,
 *   colorScheme: 'default',
 *   thresholds: {
 *     excellent: 1000,
 *     good: 2500,
 *     normal: 5000,
 *     warning: 7500,
 *     high: 10000,
 *     critical: 15000
 *   },
 *   useAverageBasedThresholds: false
 * };
 *
 * // Average-based multi-tier thresholds (default)
 * const thresholds: TokenDisplayThresholds = {
 *   enabled: true,
 *   colorScheme: 'default',
 *   useAverageBasedThresholds: true,
 *   averageMultiplierExcellent: 0.75,
 *   averageMultiplierGood: 1.0,
 *   averageMultiplierWarning: 1.5,
 *   averageMultiplierHigh: 1.75,
 *   averageMultiplierCritical: 2.0
 * };
 * ```
 */
export interface TokenDisplayThresholds {
  enabled?: boolean;
  colorScheme?: ColorScheme;
  customColors?: TokenColors;
  thresholds?: TokenThresholds;
  useAverageBasedThresholds?: boolean;
  averageMultiplierExcellent?: number;
  averageMultiplierGood?: number;
  averageMultiplierWarning?: number;
  averageMultiplierHigh?: number;
  averageMultiplierCritical?: number;
  // Legacy support for backward compatibility
  warningThreshold?: number;
  criticalThreshold?: number;
}

/**
 * Consolidated token tracking configuration
 *
 * Centralized configuration for all token-related features including
 * display settings, budget limits, and cost calculation. This provides
 * a single place to configure token tracking behavior.
 *
 * @interface TokenTrackingConfig
 * @property {boolean} [enabled] - Master toggle for all token tracking features (default: true)
 * @property {TokenDisplayThresholds} [display] - Visual indicator settings for token usage
 * @property {TokenBudget} [budget] - Budget limits and warning thresholds
 * @property {CostConfig} [costs] - Cost calculation and display settings
 *
 * @example
 * ```typescript
 * const tokenTracking: TokenTrackingConfig = {
 *   enabled: true,
 *   display: {
 *     enabled: true,
 *     useAverageBasedThresholds: true,
 *     averageMultiplierWarning: 1.5,
 *     averageMultiplierCritical: 2.0
 *   },
 *   budget: {
 *     enabled: true,
 *     maxTokens: 100000,
 *     warningThreshold: 0.8,
 *     criticalThreshold: 0.95
 *   },
 *   costs: {
 *     enabled: true,
 *     currency: 'USD',
 *     precision: 4
 *   }
 * };
 * ```
 */
export interface TokenTrackingConfig {
  enabled?: boolean;
  display?: TokenDisplayThresholds;
  budget?: TokenBudget;
  costs?: CostConfig;
}

/**
 * Summary of a complete orchestration session
 *
 * Contains comprehensive metrics about the session execution including
 * progress tracking, timing information, and optional token usage data
 * when supported by the OpenCode SDK version.
 *
 * @interface SessionSummary
 * @property {number} sessionsRun - Number of individual coding sessions executed
 * @property {number} featuresCompleted - Number of features successfully completed
 * @property {string} finalProgress - Progress in format "completed/total"
 * @property {number} completionPercentage - Percentage of features completed (0-100)
 * @property {string} elapsedTime - Total time taken in human-readable format
 * @property {boolean} isComplete - Whether all features are completed
 * @property {Object} [tokenUsage] - Token usage data if tracking is supported and available
 * @property {TokenUsage[]} tokenUsage.sessions - Array of per-session token usage
 * @property {TokenUsage} tokenUsage.total - Aggregated token usage across all sessions
 * @property {TokenUsageByModel} [tokenUsage.byModel] - Token usage breakdown by model (F024)
 *
 * @example
 * ```typescript
 * const summary: SessionSummary = {
 *   sessionsRun: 3,
 *   featuresCompleted: 2,
 *   finalProgress: "2/5",
 *   completionPercentage: 40.0,
 *   elapsedTime: "15m 32s",
 *   isComplete: false,
 *   tokenUsage: {
 *     sessions: [
 *       { input: 1200, output: 600, total: 1800 },
 *       { input: 800, output: 400, total: 1200 }
 *     ],
 *     total: { input: 2000, output: 1000, total: 3000 }
 *   }
 * };
 * ```
 */
export interface SessionSummary {
  sessionsRun: number;
  featuresCompleted: number;
  finalProgress: string;
  completionPercentage: number;
  elapsedTime: string;
  isComplete: boolean;
  tokenUsage?: {
    sessions: TokenUsage[];
    total: TokenUsage;
  };
}

export interface ValidationError {
  featureId: string;
  field: string;
  message: string;
}

export interface ValidationStats {
  total: number;
  passing: number;
  failing: number;
  byCategory: Record<string, number>;
  byPriority: Record<Priority, number>;
  tokenUsage?: {
    total: TokenUsage;
    byCategory: Record<string, TokenUsage>;
    averagePerFeature: number;
  };
}

export interface ValidationResult {
  valid: boolean;
  errors: ValidationError[];
  stats: ValidationStats;
}

export interface StatusReportOptions {
  verbose?: boolean;
  showGitLog?: boolean;
  showNextFeatures?: number;
  showProgress?: boolean;
  json?: boolean;
  minTokens?: number;
}

export interface CategoryStatus {
  passing: number;
  failing: number;
  total: number;
}

export interface StatusOutput {
  progress: {
    passing: number;
    failing: number;
    total: number;
    percentage: number;
  };
  projectName?: string;
  nextFeatures: Array<{
    id: string;
    description: string;
    priority: Priority;
    category: string;
  }>;
  byCategory?: Record<string, CategoryStatus>;
  byPriority?: Record<Priority, CategoryStatus>;
  gitLog?: string[];
  /** Description of the last session that was run */
  lastSession?: string;
  /** Token usage from the most recent session, if available */
  lastSessionTokens?: TokenUsage;
  /** Cumulative token usage across all sessions, if available */
  totalTokens?: TokenUsage;
  /** Token usage breakdown by model, if available */
  tokenUsageByModel?: TokenUsageByModel;
  workingDirectory: string;
}

export interface ValidationOutput {
  valid: boolean;
  errorCount: number;
  errors: ValidationError[];
  stats: ValidationStats;
}

export interface UpdateOutput {
  success: boolean;
  featureId: string;
  oldStatus: 'passing' | 'failing';
  newStatus: 'passing' | 'failing';
  description: string;
  category: string;
  progress: {
    passing: number;
    total: number;
    percentage: number;
  };
}

// ============================================================================
// Archive Types
// ============================================================================

/**
 * Options for the moveToArchive function
 */
export interface MoveToArchiveOptions {
  /** The path to the source file to move */
  sourcePath: string;
  /** The destination directory path */
  destDirectory: string;
  /** The filename to use in the destination (optional, defaults to original filename) */
  filename?: string;
  /** The project root directory (optional, defaults to process.cwd()) */
  projectDir?: string;
}

/**
 * Result of a successful archive operation
 */
export interface ArchiveResult {
  /** The full path to the archived file */
  destPath: string;
  /** Whether the file was successfully archived */
  success: boolean;
}

/**
 * Token efficiency metrics for a specific feature
 *
 * Tracks token consumption and efficiency for individual features,
 * allowing for analysis of which features are most/least token-intensive.
 *
 * @interface FeatureEfficiency
 * @property {string} featureId - Feature identifier (e.g., 'F021')
 * @property {string} featureDescription - Brief description of the feature
 * @property {number} tokenUsage - Total tokens used for this feature
 * @property {number} sessionCount - Number of sessions spent on this feature
 * @property {number} tokensPerSession - Average tokens per session for this feature
 * @property {number} efficiencyScore - Tokens per feature (lower is more efficient)
 *
 * @example
 * ```typescript
 * const featureEfficiency: FeatureEfficiency = {
 *   featureId: 'F021',
 *   featureDescription: 'Add JSDoc comments for token-related types',
 *   tokenUsage: 1500,
 *   sessionCount: 1,
 *   tokensPerSession: 1500,
 *   efficiencyScore: 1500
 * };
 * ```
 */
export interface FeatureEfficiency {
  featureId: string;
  featureDescription: string;
  tokenUsage: number;
  sessionCount: number;
  tokensPerSession: number;
  efficiencyScore: number;
}

/**
 * Comprehensive token efficiency analysis
 *
 * Provides aggregate efficiency metrics across all features, including
 * identification of most/least efficient features and optimization opportunities.
 *
 * @interface TokenEfficiencyMetrics
 * @property {number} totalFeatures - Total number of features with token data
 * @property {number} totalTokens - Total tokens across all analyzed features
 * @property {number} averageTokensPerFeature - Average tokens used per feature
 * @property {number} averageTokensPerSession - Average tokens used per session
 * @property {FeatureEfficiency[]} mostEfficient - Array of most token-efficient features (lowest tokens/feature)
 * @property {FeatureEfficiency[]} leastEfficient - Array of least token-efficient features (highest tokens/feature)
 * @property {string[]} optimizationOpportunities - Suggestions for improving token efficiency
 *
 * @example
 * ```typescript
 * const efficiencyMetrics: TokenEfficiencyMetrics = {
 *   totalFeatures: 15,
 *   totalTokens: 45000,
 *   averageTokensPerFeature: 3000,
 *   averageTokensPerSession: 2250,
 *   mostEfficient: [
 *     { featureId: 'F010', featureDescription: 'Add emoji indicator', tokenUsage: 500, sessionCount: 1, tokensPerSession: 500, efficiencyScore: 500 }
 *   ],
 *   leastEfficient: [
 *     { featureId: 'F015', featureDescription: 'Calculate cost estimates', tokenUsage: 8000, sessionCount: 2, tokensPerSession: 4000, efficiencyScore: 8000 }
 *   ],
 *   optimizationOpportunities: [
 *     'Consider breaking down F015 into smaller sub-features',
 *     'Review prompt engineering for high-token features'
 *   ]
 * };
 * ```
 */
export interface TokenEfficiencyMetrics {
  totalFeatures: number;
  totalTokens: number;
  averageTokensPerFeature: number;
  averageTokensPerSession: number;
  mostEfficient: FeatureEfficiency[];
  leastEfficient: FeatureEfficiency[];
  optimizationOpportunities: string[];
}

/**
 * Error information for archive operations
 */
export interface ArchiveError extends Error {
  /** Error code if available (e.g., 'ENOENT', 'EXDEV') */
  code?: string;
  /** Path that caused the error */
  path?: string;
}
